name: alethic-ism-processor-python
channels:
  - file:///Users/kasrarasaee/miniconda3/envs/local_channel
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - python-dotenv
  - pulsar-client
  - psycopg2
  - pyyaml
  - pydantic
  - pydantic-core
  - tenacity
  - restrictedpython
  - alethic-ism-core
  - alethic-ism-db
