apiVersion: v1
kind: Secret
metadata:
  name: alethic-ism-processor-python-secret
  namespace: alethic
stringData:
  LOG_LEVEL: "INFO"
  DATABASE_URL: "postgresql://<<db username>>:<<db password>>@alethic-db-service:5432/ism_db"
  MSG_URL: "pulsar://pulsar-proxy.pulsar.svc.cluster.local:6650"
  MSG_TOPIC: "ism_python_executor"
  MSG_MANAGE_TOPIC: "ism_python_executor_manage"
  MSG_TOPIC_SUBSCRIPTION: "ism_python_executor_subscription"
  .routing.yaml: |
    messageConfig:
        root_route:
          topic: ism_general
          manage_topic: ism_general_manage
          subscription: ism_general_subscription
          service_url: pulsar://pulsar-proxy.pulsar.svc.cluster.local:6650
    
        topic_routes:
          - selector: processor/monitor
            topic: ism_monitor
            manage_topic: ism_monitor_monitor
            subscription: ism_monitor_subscription
            service_url: pulsar://pulsar-proxy.pulsar.svc.cluster.local:6650
    
          - selector: state/sync/store
            topic: ism_state_sync_store
            subscription: ism_state_sync_store_subscription
            service_url: pulsar://pulsar-proxy.pulsar.svc.cluster.local:6650
